<?php

    $title = 'Login to website';
    $this->headTitle($title);
    
?>
<h1><?php $this->escapeHtml($title); ?></h1>
<?php

    $form->setAttribute('action', $this->url('access', array('action' => 'login')));
    $form->prepare();
    
    
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('nick'));
    echo $this->formRow($form->get('password'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();